const globalVar = {
  fixedStr: ["$comp", "$name", "$id", "$boss", "$division", "$position"],
  fixedPeriod: [
    "$thisYear",
    "$thisQuarter",
    "$thisMonth",
    "$thisWeek",
    "$thisWeednumber",
    "$Today",
    "$Yesterday",
    "$Tomorrow",
  ],

  convertlist: ["en:us", "cn:zh-cn", "cn:zh-tw", "jp:ja"],
  connecthead: [
    "code",
    "dbtype",
    "server",
    "database",
    "port",
    "user",
    "password",
  ],
  openDialog: false,
  openDialog1: false,
  openDialog2: false,
  openPopup: false,
  openHelp: false,
  showSpin: false,
  tf1: false,
  tf2: false,
  tf3: false,
  obj1: {},
  obj2: {},
  obj3: {},
  formEdit: false,
  elementData: "",
  formData: [],
  listData: [],
  currentData: "",
  currentLink: null,
  returnpath: null,
  allData: null,
  allModel: null,
  treeData: "",
  flatData: "",
  login: "",
  token: null,
  selectedKey: "",
  selectedKey1: null,
  currentPage: "",
  tempMenu: [],
  tempData: null,
  tempModel: null,
  tempModule: null,
  author: null,
  tempModelList: null,
  tempProject: null,
  tempSessionList: null,
  tempSession: null,
  tempTable: null,
  tempStyle: null,
  menu: [],
  adminmenu: [],
  openmenu: [],
  menuedit: false,
  showSidebar: true,
  apiUrl: "",
  projectbundle: "",
  dataviewBundle: null,
  currentStep: 0,
  subStep: 0,
  nextStep: null,
  graphdata: null,
  fullscreen: false,
  nodelink: {},
  card: {},
  optlist: [],
  modelresults: null,
  chklist: [],
  triggerChild: [],
  manipulation: null,
  paramvalue: null,
  showall: false,
  edit: false,
  help: null,
  helpLink: null,
  display: "icon",
  sortAction: false,
  searchWord: {},
  tabIndex: {},
  visiblebtn: false,
  graphclick: {},
  logicArr: [],
};

export { globalVar };
